### PR TITLE
Improved EthereumConverter to be self-contained.

### PR DESCRIPTION
**Pull request by Elland**

### CODE REVIEW

**Comment by yuliaveres** [comment]
@Elland , checks failed

**Comment by Elland** [comment]
Yes, for some reason it never finishes running a fabric script and as such, simulator hangs, something like that. Any ideas?

**Comment by yuliaveres** [comment]
nope, never had this issue

**Comment by Elland** [comment]
Yes but test target was empty before. 🤔 Can you check if the crashlytics integration requires something for CI to work? Running tests locally worked.

**Comment by yuliaveres** [comment]
don't have much time now :/ will take a look shortly

**Comment by Elland** [comment]
No hurries. I'm fine merging this as is for now, to help @marijnschilling.

**Pull request merged**
