### PR TITLE
Present splash if no user is logged into

### PR DESCRIPTION
**Pull request by yuliaveres**

### CODE REVIEW

**Comment by Elland** [comment]
Mind explaining the change, how it was broken before and how this fixes it? 😅

**Comment by yuliaveres** [comment]
Sure

**Comment by yuliaveres** [comment]
So I misunderstood the naming of RequiresSignIn flag; and used it for showing splash;
of course, by default it is NO, so now splash is never shown. it is set to YES only after user is created.

but requires sign in is " not verified ", and has nothing to do with signin + splash flow.

Now if no user logged into, meaning no current user - we show sign in.

**Comment by Elland** [comment]
Hmm, I think this is still the wrong model. 🤔 I'll try to elaborate.

**Comment by Elland** [comment]
Got it. 🚀

**Pull request merged**
