### PR TITLE
Allow user to store backup phrase even when verified

### PR DESCRIPTION
**Pull request by faymontage**

### CODE REVIEW

**Comment by Elland** [comment]
If it's already verified, it shouldn't re-verify it. Maybe change it to just show you the passphrase instead?

**Comment by faymontage** [comment]
@Elland I disagree - if my original backup is lost or unavailable, I should be able to store my phrase again, with verification steps and all.

**Comment by Elland** [comment]
🤔 good point!

**Comment by yuliaveres** [comment]
Great !

**Comment by faymontage** [comment]
@yuliaveres As the sole reviewer, please merge this.

**Pull request merged**
