### PR TITLE
Fix inconsistent presentation of alerts while scanning qr codes

### PR DESCRIPTION
**Pull request by yuliaveres**

### CODE REVIEW

**Comment by Elland** [comment]
Description, screenshots or gif or video? 👍

**Comment by yuliaveres** [comment]
just made 😄

**Comment by yuliaveres** [comment]
previous
now

**Comment by yuliaveres** [comment]
yep , basically payment confirmation was not dismissed completely when Navigator started to present alert, thus topController was still PaymentConfirmation.
as a result confirmation was dismissed shortly and error alert was never shown 😢

**Pull request merged**
